Vanilla js tasks
PechurinaLena/js-tasks pull request #1
Opened 2021-05-03 08:35 UTC by PechurinaLena

_There is no finished some tasks:_
- Task1 (A) with polyfill for a map, filter, reduce methods. Also next tasks realized without any polyfill
- Task3 (Б)
- Task4 (Б) with makeDroids function

2021-05-03 10:25 UTC, k-krasilnikova requested changes
Fix some coments please

2021-05-03 10:25 UTC, k-krasilnikova commented on task1/filterArr.js
> +const filter = notes.filter(el => el.isMarked === true )
1. Maybe it will be better to define an iterated object with more special name? 
2. Are you sure it's a good idea to check boolean values such way? Maybe we can use just "truly" check?
3. Why did you named filtered items as "filter"? Is it a function or object?
Example:
```suggestion
const filteredNotes = notes.filter(note => note.isMarked)
```

2021-05-03 10:25 UTC, k-krasilnikova commented on task1/newArr.js
> +  obj => {
Maybe it will be better to avoid unnecessary return statement? Maybe we can define `obj` as something more readale in context of `notes`?
```suggestion
notes.map(
  note => ({
    id: note.id,
    title: note.title
  })
```

2021-05-03 10:25 UTC, k-krasilnikova commented on task1/reduceArr.js
> +let sum = notes.reduce(function (accumulator, currentValue) {
1. It will be hard to detect what is the sum for other engineers, maybe it's better to use `sumOfPages` or `sumOfNotesPages` instead? 
2. Why you defined `sum` as `let variable`? Where it's changed?
3. Why you didn't use arrow function here? 
4. What is `accumulator` and what is `currentValue`? 
5. I think there is no need to use a return statement inside the function body.

```suggestion
const sumOfPages = notes.reduce((sum, note) => sum + note.pagesCount, initialValue)
```

2021-05-03 10:25 UTC, k-krasilnikova commented on task3/simplyTable.js
> +        const myStatus = document.querySelectorAll('.pending')
What is `myStatus` variable? Out of code, it looks like string or object, but here is array. Maybe it's better to use `pendingStatuses` name?

2021-05-03 10:25 UTC, k-krasilnikova commented on task3/simplyTable.js
> +        let interval = setInterval(function () {
Why let is here? Where did you change the `interval` value?

2021-05-03 10:25 UTC, k-krasilnikova commented on task3/simplyTable.js
> +            if (myStatus[i].innerHTML === 'Pending') {
Let's define all strings as constants and reuse them. For example:
```
const STATUSES = {
  pending: "Pending",
  done: "Done",
  failed: "Failed"
}
```

2021-05-03 10:25 UTC, k-krasilnikova commented on task3/simplyTable.js
> +                myStatus[i].style.color = '#85929E'
Let's define color in constants.

2021-05-03 10:25 UTC, k-krasilnikova commented on task3/simplyTable.js
> +            if (++i === myStatus.length) {
It's not a good idea to use such iterators. Try to avoid it in the future due to high risks.

2021-05-03 10:25 UTC, k-krasilnikova commented on task3/simplyTable.js
> +        }, 5000)
Define those Magic Numbers as contsants

2021-05-03 10:25 UTC, k-krasilnikova commented on task3/simplyTable.js
> +let mybtn = document.getElementById('btn')
Why `let`?

2021-05-03 10:25 UTC, k-krasilnikova commented on task3/simplyTable.js
> +let mybtn = document.getElementById('btn')
In common everything works good, but not obviously solution. Lets change algorithm to something more readable:
```
setTimeout(function () {
        const interval = setInterval(function () {
        console.log('Check started')
        const pendingStatuses = document.querySelectorAll('.pending')
        const countOfElementsToChange = pendingStatuses.length
        if (countOfElementsToChange) {
          pendingStatuses[0].classList.remove('pending')
          pendingStatuses[0].innerHTML = 'Done'
          pendingStatuses[0].style.color = '#85929E'
        } else {
          clearInterval(interval)
        }
```

2021-05-03 10:25 UTC, k-krasilnikova commented on task4/newPromise.js
> +    let promise = new Promise((resolve, reject) => {
Are you sure that we need to use `let` here?

2021-05-03 10:25 UTC, k-krasilnikova commented on task4/newPromise.js
> +            let current = Math.floor(Math.random() * 8 + 1)
Are you sure that we need to use `let` here?

2021-05-03 12:26 UTC, PechurinaLena commented
Fixed code and add 2 more tasks:
- Task3 (Б)
- Task4 (Б)

2021-05-03 14:53 UTC, k-krasilnikova requested changes
More fixes required

2021-05-03 14:53 UTC, k-krasilnikova commented on task1/newArr.js
> +    return {
Can you please remove `return` and return an object using arrow function?

2021-05-03 14:53 UTC, k-krasilnikova commented on task1/reduceArr.js
> +let initialValue = 0
Are you sure that we need to use let?

2021-05-04 12:12 UTC, k-krasilnikova approved these changes
Good job!

2021-05-04 12:47 UTC, merged